arch: aarch64

# Available Platform:
#   Allwinner
#   Amlogic
#   Broadcom (BCM2835)
#   Hisilicon
#   Qualcomm
#   Virtio (QEMU)
#   Rockchip

pacman:
  install:
  # For regulatory.db
  - wireless-regdb

  # Universal Kernel
  - linux-asahi

  # Need load kernel modules
  - mkinitcpio

kernel:
  kernel: vmlinuz-linux-asahi
  initramfs: initramfs-linux-asahi.img

scripts:
- stage: pre-initramfs
  chroot: yes
  code: |
    mods="$$(pacman -Qql linux-asahi | grep -E '^/usr/lib/modules/[0-9]*\.[0-9]*\.[0-9]*[^/]*/$$')"
    rm --one-file-system -rf /boot/dtbs
    cp -a "$$mods/dtbs" /boot/dtbs
